<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * EventTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeRepository extends EntityRepository
{
  public function findAllActive(\Entities\Event $event = null){
    return $eventtypes = $this->findBy(array('isActive'=>true));
    if($event instanceof \Entities\Event){
      if(!$eventtypes->contains($event->getType())){
              $eventtypes->add( $event->getType());
      }
    }
    return $eventtypes;
  }
}