<?php
namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;
use Entities;

/**
 * ResponsibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsibilityRepository extends EntityRepository{
  public function getResponsibilityArray($lang = 'no'){
    $responsibilities = $this->findAllActive();
    $ret = array();
    foreach($responsibilities as $responsibility){
      $ret[$responsibility->getName($lang)] = $responsibility;
    }
    return $ret;
  }
  /**
   *
   * @return \Entities\Responsibility
   */
  public function findAllActive(){
    return $this->findBy(array('active'=>1));
  }
}