<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  /**
   *
   * @param stirng $anything Søk etter en bruker basert på navn, epost eller telefonnummer
   * @return \Entities\User
   */
  public function search($anything){
    if(!$anything){
      return NULL; // Greit å ikke være redd for å sende bortkastede query'er
    }
    $q = $this->getEntityManager()
              ->createQuery('SELECT u FROM \Entities\User u WHERE u.fullname = :any OR u.email = :any OR u.mobilephone = :any')
              ->setParameter('any', $anything);
    try{
      $user =  $q->getSingleResult();
    }catch (\Exception $e){
      return NULL;
    }
    return $user;
  }
  public function getMembers(\DateTime $time = null) {
    if (!isset($time)){
      $time = new \DateTime('now');
    }
    $q = $this->getEntityManager()
            ->createQuery('SELECT u FROM \Entities\User u WHERE u.internalkey IN (SELECT m.medlem FROM \Entities\Medlemskap m WHERE m.start < :time AND m.slutt > :time) ORDER BY u.fullname')
            ->setParameter('time', $time->format('Y-m-d'));
    try {
      return $q->getResult();
    } catch (Exception $exc) {
      return NULL;
    }

  }
}