<?php

namespace Entities\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
  /**
   *
   * @param stirng $anything Søk etter en bruker basert på navn, epost eller telefonnummer
   * @return \Entities\User
   */
  public function search($anything){
    if(!$anything){
      return NULL; // Greit å ikke være redd for å sende bortkastede query'er
    }
    $q = $this->getEntityManager()
              ->createQuery('SELECT u FROM \Entities\User u JOIN u.atteributes a WHERE a.fullname = :any OR a.email = :any OR a.mobilephone = :any')
              ->setParameter('any', $anything);
    try{
      $user =  $q->getSingleResult();
    }catch (\NoResultException $e){
      return NULL;
    }
    return $user;
  }
  public function getMembers(\DateTime $time = null,$showHidden = false) {
    if (!isset($time)){
      $time = new \DateTime('now');
    }
    $q = $this->getEntityManager()->createQueryBuilder()
            ->select('u,a')
            ->from('\Entities\User', 'u')
            ->leftJoin('u.atteributes', 'a')
            ->where('u.id IN (SELECT m.medlem FROM \Entities\Medlemskap m WHERE m.start < :time AND m.slutt > :time)')
            ->setParameter('time', $time->format('Y-m-d'))
            ->orderBy('a.fullname');
    if(!$showHidden){
      $q->andWhere('a.hemmelig = 0');
    }
    return $q->getQuery()->getResult();
  }
  public function find($id){
    $q = $this->getEntityManager()->createQueryBuilder()
            ->select('u,a')
            ->from('\Entities\User', 'u')
            ->leftJoin('u.atteributes', 'a')
            ->where('u.id = ?1')
            ->setParameter(1, $id,'integer');
    try {
      return $q->getQuery()->getSingleResult();
    } catch (\Doctrine\ORM\NoResultException $exc) {
      return NULL;
    }
  }
}